# Generated by Django 3.1.5 on 2021-02-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_remove_wishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='a_id',
            field=models.CharField(max_length=20),
        ),
    ]
