# Generated by Django 3.1.5 on 2021-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20210208_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='a_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
