# Generated by Django 3.1.3 on 2020-11-26 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0002_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='participants',
            field=models.ManyToManyField(related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
