# Generated by Django 3.1.5 on 2021-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20201126_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='request',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
