# Generated by Django 3.1.5 on 2021-03-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_auto_20210301_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='request',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
