# Generated by Django 3.1.7 on 2021-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_auto_20210301_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='request',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
