# Generated by Django 3.1.3 on 2020-11-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
