# Generated by Django 3.1.3 on 2020-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_events_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
