# Generated by Django 3.1.3 on 2020-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='request',
            field=models.BooleanField(default=True),
        ),
    ]
