# Generated by Django 3.1.3 on 2020-12-02 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201202_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='date_type',
            field=models.CharField(blank=True, choices=[('🏓 Sports', '🏓 Sports'), ('💃 Music', '💃 Music'), ('🍿 Film', '🍿 Film'), ('♟️ Indoor', '♟️ Indoor'), ('🎡 Outdoor', '🎡 Outdoor'), ('🏕️ Travel', '🏕️ Travel'), ('🍩 Food', '🍩 Food')], max_length=100),
        ),
    ]
