# Generated by Django 3.1.5 on 2021-02-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210219_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
