# Generated by Django 3.1.5 on 2021-02-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210219_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_type',
            field=models.CharField(blank=True, choices=[('🏓', '🏓'), ('💃', '💃'), ('🍿', '🍿'), ('♟️', '♟️'), ('🎡', '🎡'), ('🏕', '🏕'), ('🍩', '🍩')], max_length=100),
        ),
    ]
