# Generated by Django 3.1.5 on 2021-01-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0003_auto_20201126_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('direction', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_list', to='connections.connections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'f_id', 'connection')},
            },
        ),
    ]
