# Generated by Django 3.1.5 on 2021-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
