# Generated by Django 3.1.5 on 2021-02-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activities_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='completed',
        ),
    ]
