# Generated by Django 3.1.5 on 2021-02-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
