# Generated by Django 3.1.5 on 2021-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
