# Generated by Django 3.1.5 on 2021-02-24 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_notes_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_notes', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
