# Generated by Django 3.1.5 on 2021-02-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='sender',
        ),
    ]
