# Generated by Django 3.1.4 on 2020-12-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='genres',
        ),
    ]
