# Generated by Django 3.1.4 on 2020-12-05 02:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201205_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None),
        ),
    ]
