# Generated by Django 3.1.4 on 2020-12-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='m_id',
            field=models.IntegerField(),
        ),
    ]
