# Generated by Django 3.1.4 on 2020-12-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movies_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='name',
        ),
    ]
