# Generated by Django 3.1.4 on 2021-01-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20201126_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_auto_20201220_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='m_id',
            new_name='f_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='connection',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='movies_list', to='connections.connections'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together={('user', 'f_id', 'connection')},
        ),
    ]
