# Generated by Django 3.1.5 on 2021-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210118_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
