# Generated by Django 3.1.5 on 2021-02-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movies_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='completed',
        ),
    ]
