# Generated by Django 3.1.4 on 2020-12-11 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20201126_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_auto_20201209_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='connection',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='food_list', to='connections.connections'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('user', 'f_id')},
        ),
    ]
