# Generated by Django 3.1.4 on 2020-12-17 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_auto_20201126_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_food_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('user', 'f_id', 'connection')},
        ),
    ]
