# Generated by Django 3.1.5 on 2021-01-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20201217_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='img',
        ),
    ]
