# Generated by Django 3.1.5 on 2021-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
