# Generated by Django 3.1.5 on 2021-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210218_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_id',
            field=models.CharField(default=False, max_length=300),
            preserve_default=False,
        ),
    ]
