# Generated by Django 3.1.5 on 2021-02-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210218_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='completed',
        ),
    ]
